name: Python package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install library
        run: |
          pip install requests
          pip install beautifulsoup4
          pip install lxml
          pip install pandas
          pip install selenium
          pip install webdriver_manager

      - name: Run script
        run: |
          python pychart_M_total.py

      - name: Check for changes
        id: check_changes
        run: |
          git config --global user.email "dlswl1993@gmail.com"
          git config --global user.name "HwangInJi"
          git add musicaldata/pychart_M_total_*.json
          if git diff --cached --exit-code; then
            echo "::set-output name=changes::no"
          else
            echo "::set-output name=changes::yes"
          fi

      - name: Commit changes
        if: steps.check_changes.outputs.changes == 'yes'
        run: |
          git commit -m "차트 수집 완료" || echo "No changes to commit"

      - name: Push changes
        if: steps.check_changes.outputs.changes == 'yes'
        uses: ad-m/github-push-action@master
        with:
          branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Debugging Information
        run: |
          echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"
          git status
          git log -1
